# Optimization

In [1]:
import pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PowerTransformer
from scipy.optimize import fmin, minimize

In [3]:
# Load dataframes from binary files
base_dir = r'C:\FBr\Weiterbildung\Project\GitHub\sep24_cds_int_us-welding'
#base_dir = r'D:\Entwicklungen\share\DataScienceProject\sep24_cds_int_us-welding'

ft_param_path = os.path.join(base_dir, 'ft_files', '03_feat_parameters.ft')
df_params = pd.read_feather(ft_param_path)

dump_dir = os.path.join(base_dir, 'model_dumps')

In [4]:
# List of parameters
lst_param = df_params.columns.to_list()

lst_var = lst_param[1:4] + lst_param[5:7] + lst_param[8:24]
lst_nb_slots = [lst_param[4]] + [lst_param[7]]
lst_calc = lst_param[32:34]
lst_slot_class = lst_param[541:545]
lst_cols = lst_var + lst_calc + lst_slot_class

In [5]:
X = df_params[lst_cols]

In [6]:
# Get indices of Train-Test split
X_train, X_test, _, _ = train_test_split(X, X, test_size=0.2, random_state=55)
idx_train = X_train.index
idx_test = X_test.index

Target variables

In [7]:
## Long displacements
y_nrdd = df_params['long_disp_nrdd']
y_nrdd_train = y_nrdd.loc[idx_train]
y_nrdd_test = y_nrdd.loc[idx_test]

In [8]:
## All Frequencies
lst_freq = lst_param[86:122]
Y_freq = df_params[lst_freq]
Y_freq_test = Y_freq.loc[idx_test]

In [9]:
## Long frequencies
y_longfreq = df_params['freq_long']
y_longfreq_test = y_longfreq.loc[idx_test]

Long displacements

In [10]:
transf_longdisp = pickle.load(open(os.path.join(dump_dir, '5_model_neuralnetw_tuned_transformer.pkl'), 'rb'))
pipe_tuned_longdisp = pickle.load(open(os.path.join(dump_dir, '5_model_neuralnetw_tuned_long_displacements.pkl'), 'rb'))

# Apply the power transformer to the NRDD variable
w_test = transf_longdisp.transform(y_nrdd_test.values.reshape(-1, 1))

print ('Score of the test set:', pipe_tuned_longdisp.score(X_test, w_test))

Score of the test set: 0.8550440040374117

All frequencies

In [11]:
pipe_tuned_allfreq = pickle.load(open(os.path.join(dump_dir, '4_model_lgbm_tuned_all_frequencies.pkl'), 'rb'))
print ('Score of the test set:', pipe_tuned_allfreq.score(X_test, Y_freq_test))

Score of the test set: 0.9975845732050838

Long frequency

In [12]:
pipe_tuned_longfreq = pickle.load(open(os.path.join(dump_dir, '4_model_lgbm_tuned_long_frequencies.pkl'), 'rb'))
print ('Score of the test set:', pipe_tuned_longfreq.score(X_test, y_longfreq_test))

Score of the test set: 0.9933359528253154

## Select the design point with the minimum cost

In [13]:
# ID 1647 for example
id_01 = y_nrdd.argmin()

print (id_01)
print(y_nrdd[[id_01]])

x_01 = X.loc[id_01].tolist()

1647
1647    1.291901
Name: long_disp_nrdd, dtype: float64

In [14]:
pd.DataFrame([x_01], columns=lst_cols)

,dim_x,dim_y,dim_z,slot_x_length,slot_x_distance,slot_z_length,slot_z_distance,chamfer_x_dim_y,chamfer_x_dim_z,chamfer_y_dim_x,...,cut_x_depth,cut_z_start,cut_z_end,cut_z_depth,seg_x_out,seg_z_out,slot_2-2,slot_3-2,slot_4-1,slot_4-2
0,173.11,122.93,240.8,74.851,48.149,77.13,53.2,4.1767,14.899,6.5351,...,0.3487,23.429,63.553,2.1605,48.1765,59.955,0.0,0.0,0.0,1.0

In [15]:
# Predictions of all models
def fea_pred(x):
    """
    x is list
    """

    x1 = pd.DataFrame([x], columns=lst_cols)

    # Longitudinal frequency
    freq_long = pipe_tuned_longfreq.predict(x1)[0]
    # All frequencies
    all_freq = pipe_tuned_allfreq.predict(x1)[0]
    # NRDD

    nrdd_transf = pipe_tuned_longdisp.predict(x1)
    nrdd = transf_longdisp.inverse_transform(nrdd_transf)

    # Position of the long. mode
    delta_f = abs(all_freq-freq_long)
    id_long = delta_f.argmin()

    return freq_long, all_freq, nrdd[0][0], id_long

In [16]:
f_long, f_all, nrdd, idx = fea_pred(x_01) 
print (f_long, '\n', f_all, '\n', nrdd, '\n', idx)

19252.72063732115
 [15260.27828227 15500.95683153 15599.54872674 15778.35841546
 15854.66728733 15908.47609677 15954.75439044 16023.66548765
 16033.27619731 16067.6331695  16142.872227   16403.63348786
 16443.07674304 16627.62247429 17097.06668295 17189.85312716
 17545.9414874  17679.7921517  17730.11106395 17902.47973162
 18414.82486541 18597.81419491 18662.80172641 18783.44023314
 18849.07959636 18873.26235529 19011.06742396 19091.63045942
 19279.80593494 19464.58127239 20375.83518321 20571.33844436
 20654.41997341 21226.59906278 22011.44300131 22064.09764223]
 1.6892109
 28

In [17]:
weights = {'f_long': 1/0.0006440096234678033, 'nrdd': 1/5.806682727065343, 'f_all': 1/0.12581713798880445}

In [ ]:
# cost function calculated with x
def f_cost(x, weights):
    weight_f_long = weights['f_long']
    weight_nrdd = weights['nrdd']
    weight_f_all = weights['f_all']

    f_long, f_all, nrdd, idx = fea_pred(x) 

    cost_f_long = weight_f_long * ((f_long-20e3)/20e3)**2
    cost_nrdd = weight_nrdd * nrdd

    f0 = f_all[idx]
    cost_f_below = (1/(f_all[idx-1]-f0))**2
    cost_f_above = (1/(f_all[idx+1]-f0))**2
    cost_f_all = weight_f_all * (cost_f_below + cost_f_above)

    return {'cost_f_long': cost_f_long, 'cost_nrdd': cost_nrdd, 'cost_f_all': cost_f_all}

In [19]:
f_cost(x_01, weights)

{'cost_f_long': 2.1677721323431,
 'cost_nrdd': 0.2909080745621086,
 'cost_f_all': 0.0004572517349875102}

Calculate the cost functions for all design points. Then calculate the mean values in order to determine the optimal weights

In [45]:
def calc_cost_list(row):
    lst_row = row.to_list()
    return list(f_cost(lst_row, weights).values())

lst_row = df_params.loc[id, lst_cols].tolist()
calc_cost_list(df_params.loc[id, lst_cols])

[2.3252742980629297, 0.7908514826980171, 0.0013769790876557702]

In [ ]:
df_params[['cost_f_long', 'cost_nrdd', 'cost_f_all']] = df_params[lst_cols].apply(calc_cost_list, axis=1)

KeyboardInterrupt:

In [ ]:
# for id in [0]: #df_params.index:
#     print ('Index: ', id, ' / ', len(df_params.index)-1)
#     lst_row = df_params.loc[id, lst_cols].tolist()
#     costs = f_cost(lst_row, weights)
    
#     df_params.loc[id, 'cost_f_long'] = costs['cost_f_long']
#     df_params.loc[id, 'cost_nrdd'] = costs['cost_nrdd']
#     df_params.loc[id, 'cost_f_all'] = costs['cost_f_all']

Index:  0  /  7989

In [20]:
print ('mean(cost_f_long):', df_params['cost_f_long'].mean())
print ('mean(cost_nrdd):', df_params['cost_nrdd'].mean())
print ('mean(cost_f_all):', df_params['cost_f_all'].mean())

KeyError: 'cost_f_long'

In [ ]:
#weights = {'f_long': 1/0.0006440096234678033, 'nrdd': 1/5.806682727065343, 'f_all': 1/0.12581713798880445}

In [ ]:
# Complete DataFrame with the cost values
df_params

,dp_no,dim_x,dim_y,dim_z,nb_slots_x,slot_x_length,slot_x_distance,nb_slots_z,slot_z_length,slot_z_distance,...,disp_long_399,sum_sensi,coupling_long,slot_2-2,slot_3-2,slot_4-1,slot_4-2,cost_f_long,cost_nrdd,cost_f_all
0,1001,175.06,121.95,240.31,4,75.993,43.235,2,78.219,59.508,...,0.151599,3.405414e-16,0.960466,0,0,0,1,2.325274,0.790851,0.001377
1,1002,173.45,122.77,238.13,4,81.168,45.859,2,78.924,57.208,...,0.143682,5.401730e-17,0.956635,0,0,0,1,NaN,NaN,NaN
2,1003,175.85,116.71,238.10,4,77.532,45.260,2,80.099,49.215,...,0.284010,2.678586e-18,0.986845,0,0,0,1,NaN,NaN,NaN
3,1004,173.51,116.37,238.30,4,82.428,51.007,2,74.757,50.840,...,0.186770,8.933099e-18,0.967459,0,0,0,1,NaN,NaN,NaN
4,1005,175.60,118.72,241.04,4,76.576,45.981,2,78.773,64.702,...,0.293833,8.025438e-18,0.991598,0,0,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7985,11995,175.18,119.50,239.53,2,78.314,80.925,2,77.038,54.535,...,0.175034,1.445371e-17,0.960601,1,0,0,0,NaN,NaN,NaN
7986,11996,176.27,117.29,240.59,2,77.933,71.773,2,79.789,63.279,...,0.332184,3.340311e-16,0.888124,1,0,0,0,NaN,NaN,NaN
7987,11997,174.01,117.81,239.26,2,80.402,81.905,2,79.398,60.146,...,0.266484,3.313740e-18,0.964230,1,0,0,0,NaN,NaN,NaN
7988,11998,174.61,119.50,239.41,2,74.848,74.107,2,74.870,57.402,...,-0.236469,1.190454e-15,0.606705,1,0,0,0,NaN,NaN,NaN
7989,11999,176.58,122.07,238.37,2,78.904,68.789,2,77.839,61.872,...,0.165075,6.992687e-18,0.978124,1,0,0,0,NaN,NaN,NaN

Find the design point x_0 with the minimal cost function

In [ ]:
# Note the slot class
df_params['cost'] = df_params['cost_f_long'] + df_params['cost_nrdd'] + df_params['cost_f_all']

In [24]:
plt.scatter(range(len(df_params)), np.log10(df_params['cost']))

KeyError: 'cost'

In [ ]:
idx_0 = df_params['cost'].idxmin()
print ('Index:', idx_0)

Index: 1152

In [49]:
idx_0 = 1152

In [50]:
df_params.loc[[idx_0]]

,dp_no,dim_x,dim_y,dim_z,nb_slots_x,slot_x_length,slot_x_distance,nb_slots_z,slot_z_length,slot_z_distance,...,disp_long_399,sum_sensi,coupling_long,slot_2-2,slot_3-2,slot_4-1,slot_4-2,cost_f_long,cost_nrdd,cost_f_all
1152,2153,175.51,119.21,241.21,4,75.641,53.089,2,76.463,49.445,...,0.290752,4.342749e-18,0.991657,0,0,0,1,NaN,NaN,NaN

In [108]:
xvar_0 = df_params.loc[idx_0, lst_var].tolist()
xvar_55 = df_params.loc[55, lst_var].tolist()

In [109]:
df_params.loc[idx_0, lst_cols]

dim_x               175.51
dim_y               119.21
dim_z               241.21
slot_x_length       75.641
slot_x_distance     53.089
slot_z_length       76.463
slot_z_distance     49.445
chamfer_x_dim_y     11.367
chamfer_x_dim_z     8.8571
chamfer_y_dim_x     10.448
chamfer_y_dim_z     6.0016
chamfer_z_dim_x     7.8842
chamfer_z_dim_y     13.908
elefoot_x          0.76625
elefoot_z          0.23867
cut_x_start         30.419
cut_x_end           70.146
cut_x_depth          4.489
cut_z_start         29.596
cut_z_end           63.282
cut_z_depth         1.3673
seg_x_out          40.9715
seg_z_out          63.0325
slot_2-2                 0
slot_3-2                 0
slot_4-1                 0
slot_4-2                 1
Name: 1152, dtype: object

In [156]:
# function x_var --> x
def f_xvar2x(xvar, nb_slots_x, nb_slots_z):

    xvar = np.array(xvar, dtype=float).copy()

    dim_z = xvar[2]
    dim_x = xvar[0]
    slot_x_distance = xvar[4]
    slot_z_distance = xvar[6]
    seg_x_out = (dim_z-(nb_slots_x-1)*slot_x_distance)/2
    seg_z_out = (dim_x-(nb_slots_z-1)*slot_z_distance)/2
    x_calc = [seg_x_out, seg_z_out]

    if (nb_slots_x == 2) & (nb_slots_z == 2):
        x_slot_classes = [1, 0, 0, 0]
    if (nb_slots_x == 3) & (nb_slots_z == 2):
        x_slot_classes = [0, 1, 0, 0]
    if (nb_slots_x == 4) & (nb_slots_z == 1):
        x_slot_classes = [0, 0, 1, 0]
    if (nb_slots_x == 4) & (nb_slots_z == 2):
        x_slot_classes = [0, 0, 0, 1]

    #return xvar + x_calc + x_slot_classes
    return np.concatenate([xvar, x_calc, x_slot_classes])

f_xvar2x(xvar_0, 4, 2)

array([1.75510e+02, 1.19210e+02, 2.41210e+02, 7.56410e+01, 5.30890e+01,
       7.64630e+01, 4.94450e+01, 1.13670e+01, 8.85710e+00, 1.04480e+01,
       6.00160e+00, 7.88420e+00, 1.39080e+01, 7.66250e-01, 2.38670e-01,
       3.04190e+01, 7.01460e+01, 4.48900e+00, 2.95960e+01, 6.32820e+01,
       1.36730e+00, 4.09715e+01, 6.30325e+01, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 1.00000e+00])

In [159]:
# new cost function calculated with x_var
def f_cost2(xvar, weight_f_long, weight_nrdd, weight_f_all):

    x = f_xvar2x(xvar, 4, 2)

    f_long, f_all, nrdd, idx = fea_pred(x) 

    cost_f_long = weight_f_long * ((f_long-20e3)/20e3)**2
    cost_nrdd = weight_nrdd * nrdd

    f0 = f_all[idx]
    eps = 1e-8
    cost_f_below = (1/(f_all[idx-1]-f0) + eps)**2
    cost_f_above = (1/(f_all[idx+1]-f0) + eps)**2
    cost_f_all = weight_f_all * (cost_f_below + cost_f_above)
    cost_sum = cost_f_long + cost_nrdd + cost_f_all

    if not np.isfinite(cost_sum):
        print("Non-finite cost detected!", xvar)
        return 1e9

    print('xvar:', xvar)
    print('cost:', cost_sum)

    return cost_sum
    #return {'cost_f_long': cost_f_long, 'cost_nrdd': cost_nrdd, 'cost_f_all': cost_f_all}

# Test the new function
f_cost2(xvar_0, weights['f_long'], weights['nrdd'], weights['f_all'])

xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323

0.29596161675608323

In [62]:
# Compare with the full point
x_0 = df_params.loc[idx_0, lst_cols].tolist()
f_cost(x_0, weights)

{'cost_f_long': 0.009187046878192533,
 'cost_nrdd': 0.2864489067096137,
 'cost_f_all': 0.0003256634491888921}

In [170]:
# Definitions of the bounds
var_bounds = [(173.0, 177.0), (115.0, 125.0), (238.0, 242.0), (74.0, 83.0), (41.0, 55.0), (74.0, 83.0), (49.0, 67.0), (0.1, 20.0), (0.1, 20.0), (0.1, 20.0), (0.1, 20.0),
          (0.1, 20.0), (0.1, 20.0), (0.1, 5.0), (0.1, 5.0), (20.0, 60.0), (60.0, 100.0), (0.1, 5.0), (20.0, 45.0), (45.0, 70.0), (0.1, 5.0)]

In [86]:
weight_f_long = 1552.7718275625957
weight_nrdd = 0.17221536753488045
weight_f_all = 7.948042818212752

In [ ]:
bres = minimize(
    f_cost2,
    xvar_0,
    args=(weight_f_long, weight_nrdd, weight_f_all),  # constants
    method='L-BFGS-B',   # supports bounds
    bounds=var_bounds,
    options={'maxiter': 500}
)
print('Success:', res.success)
print('Optimal x:', res.x)
print('Optimal cost:', res.fun)

xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.75510000e+02 1.19210000e+02 2.41210000e+02 7.56410000e+01
 5.30890000e+01 7.64630000e+01 4.94450000e+01 1.13670000e+01
 8.85710001e+00 1.04480000e+01 6.00160000e+00 7.88420000e+00
 1.39080000e+01 7.66250000e-01 2.38670000e-01 3.04190000e+01
 7.01460000e+01 4.48900000e+00 2.95960000e+01 6.32820000e+01
 1.36730000e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.75510000e+02 1.19210000e+02 2.41210000e+02 7.56410000e+01
 5.30890000e+01 7.64630000e+01 4.94450000e+01 1.13670000e+01
 8.85710000e+00 1.04480000e+01 6.00160001e+00 7.88420000e+00
 1.39080000e+01 7.66250000e-01 2.38670000e-01 3.04190000e+01
 7.01460000e+01 4.48900000e+00 2.95960000e+01 6.32820000e+01
 1.36730000e+00]
cost: 0.29596161675608323
xvar: [1.75510000e+02 1.19210000e+02 2.41210000e+02 7.56410000e+01
 5.30890000e+01 7.64630000e+01 4.94450000e+01 1.13670000e+01
 8.85710000e+00 1.04480000e+01 6.00160000e+00 7.88420001e+00
 1.39080000e+01 7.66250000e-01 2.38670000e-01 3.04190000e+01
 7.01460000e+01 4.48900000e+00 2.95960000e+01 6.32820000e+01
 1.36730000e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551000e+02 1.1921000e+02 2.4121000e+02 7.5641000e+01 5.3089000e+01
 7.6463000e+01 4.9445000e+01 1.1367000e+01 8.8571000e+00 1.0448000e+01
 6.0016000e+00 7.8842000e+00 1.3908000e+01 7.6625001e-01 2.3867000e-01
 3.0419000e+01 7.0146000e+01 4.4890000e+00 2.9596000e+01 6.3282000e+01
 1.3673000e+00]
cost: 0.29596161675608323
xvar: [1.7551000e+02 1.1921000e+02 2.4121000e+02 7.5641000e+01 5.3089000e+01
 7.6463000e+01 4.9445000e+01 1.1367000e+01 8.8571000e+00 1.0448000e+01
 6.0016000e+00 7.8842000e+00 1.3908000e+01 7.6625000e-01 2.3867001e-01
 3.0419000e+01 7.0146000e+01 4.4890000e+00 2.9596000e+01 6.3282000e+01
 1.3673000e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.75510000e+02 1.19210000e+02 2.41210000e+02 7.56410000e+01
 5.30890000e+01 7.64630000e+01 4.94450000e+01 1.13670000e+01
 8.85710000e+00 1.04480000e+01 6.00160000e+00 7.88420000e+00
 1.39080000e+01 7.66250000e-01 2.38670000e-01 3.04190000e+01
 7.01460000e+01 4.48900001e+00 2.95960000e+01 6.32820000e+01
 1.36730000e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
cost: 0.29596161675608323
xvar: [1.75510000e+02 1.19210000e+02 2.41210000e+02 7.56410000e+01
 5.30890000e+01 7.64630000e+01 4.94450000e+01 1.13670000e+01
 8.85710000e+00 1.04480000e+01 6.00160000e+00 7.88420000e+00
 1.39080000e+01 7.66250000e-01 2.38670000e-01 3.04190000e+01
 7.01460000e+01 4.48900000e+00 2.95960000e+01 6.32820000e+01
 1.36730001e+00]
cost: 0.29596161675608323
Success: True
Optimal x: [1.7551e+02 1.1921e+02 2.4121e+02 7.5641e+01 5.3089e+01 7.6463e+01
 4.9445e+01 1.1367e+01 8.8571e+00 1.0448e+01 6.0016e+00 7.8842e+00
 1.3908e+01 7.6625e-01 2.3867e-01 3.0419e+01 7.0146e+01 4.4890e+00
 2.9596e+01 6.3282e+01 1.3673e+00]
Optimal cost: 0.29596161675608323

In [169]:
res = differential_evolution(
    f_cost2,
    args=(weight_f_long, weight_nrdd, weight_f_all),  # constants
    bounds=var_bounds,
    polish=False
)
print('Success:', res.success)
print('Optimal x:', res.x)
print('Optimal cost:', res.fun)

xvar: [1.00175632e+02 1.16082685e+02 2.38870035e+02 7.97477140e+01
 5.24094573e+01 7.41238817e+01 5.15745078e+01 1.72530132e+01
 1.23136585e+01 1.00562291e+01 4.10288142e+00 1.43920254e+01
 1.43929030e+01 7.67464459e-01 1.15509771e-01 5.52377984e+01
 7.80739171e+01 2.29673080e+00 3.87994735e+01 5.86383290e+01
 8.09104882e-01]
cost: 2.219818794241497
xvar: [161.81676706 122.24310042 240.04280816  77.03393377  41.40831922
  80.12858215  66.92664192   4.0667817   10.33332673  15.74243718
   7.3283659   17.35054439  16.31598228   4.22008308   0.79919482
  41.2218046   77.52514586   0.27705223  36.4758737   55.97503089
   4.04976981]
cost: 2.453580579536631
xvar: [134.02849476 120.08519714 240.27964571  74.81802708  54.30567312
  77.66105908  66.86783269   1.16658135   7.20916349   4.82526203
  14.33825363   2.30990888  13.42023622   0.68036294   1.36512754
  30.44762298  85.9207987    0.70369854  20.73108243  62.96811514
   4.68083553]
cost: 1.5421350832707084
xvar: [112.26735669 122.40586106 238.26391129  74.68211682  53.82819374
  81.49057422  62.12929085  18.5943063   19.31804138  14.17730917
   1.8243297   18.84602063   0.39142685   1.5555278    1.50443034
  36.9893442   72.65628132   3.19168874  38.0485089   58.32675434
   3.86849586]
cost: 2.171548813408491
xvar: [166.87011983 118.18678309 238.85307079  75.30113627  41.48928878
  79.32459751  50.62157633  11.25481944   2.29509811   2.23879961
  14.88263696   4.86331986  19.26574128   1.42634515   1.938554
  51.90812233  79.3084999    3.95164462  35.38485586  45.7149496
   1.28556273]
cost: 0.7035757609527925
xvar: [103.3078063  118.30655318 239.79886274  82.90914506  50.8062833
  82.15021633  65.62255731  13.31132562   6.63902943   8.89535017
   3.10766329   7.12149922   8.97863608   1.0154842    2.10107118
  55.62545976  99.3986248    0.36856642  37.17375731  63.99540073
   4.98661263]
cost: 1.3178813876173123
xvar: [180.49186731 123.89791171 239.30326011  75.43263262  42.23898063
  79.1223429   58.92565706  17.89947676  11.15143899  12.97850874
  17.60759671   1.73890854  10.07157327   0.96923316   1.18899608
  59.88027777  82.032864     2.92382077  34.0374907   52.81129635
   3.72327263]
cost: 3.339200964075872
xvar: [163.01947274 116.56229149 239.15894228  82.57816777  41.63955846
  80.5898764   54.69298516  10.61149311   9.93841268   2.29366996
  11.88558948   0.58727723   3.60047393   3.93012784   2.08780979
  20.89482732  97.94482142   4.90995876  34.11428061  46.88499102
   0.89713981]
cost: 1.5523670341650597
xvar: [141.09215248 122.73557834 238.45219738  77.11815889  41.22213043
  77.07092215  60.15512144  17.71687531   4.12075447   4.22583627
  10.0265051   10.48504821  18.72194782   0.71543281   4.96619769
  21.69689153  71.79899845   3.50019761  26.24420136  64.73580329
   3.49211764]
cost: 3.37801809802505
xvar: [158.46923751 123.14086408 238.52439379  81.18541569  43.87913716
  75.88076786  57.97035684   8.31759345   8.63578367  16.55734025
  13.75019396   4.57521022  13.87060766   1.10664506   1.82994933
  41.47667465  90.70871597   3.01124805  25.44315005  54.81584764
   0.84554368]
cost: 3.713807861813052
xvar: [168.42741234 116.0018673  241.19527712  77.81531211  45.24336599
  74.15971215  57.01828837  12.04493109  11.34990854   1.97646923
  14.01858596  13.54497332  19.46351425   1.29888081   0.40918829
  52.38932316  88.29465805   1.38688326  37.89863249  46.1672003
   1.52209269]
cost: 1.8890936567655578
xvar: [135.75524688 123.82508247 238.90463483  75.64320391  54.89949459
  82.27425314  49.52047415  11.51132359   2.34155776  14.51101945
   0.57003328   5.42562978   4.01072321   0.4677872    4.38517887
  56.55677066  70.14440398   3.96791132  28.93089875  62.70381255
   2.13971718]
cost: 5.005969048728296
xvar: [196.27961322 119.64180943 241.35327486  80.95541397  44.61186638
  80.66470437  53.58249879   1.30921604   7.91496744   1.44773676
  15.02585924   7.40432172  13.65620329   2.59486846   3.33703468
  42.78144136  86.36006741   1.22413678  39.09279169  62.59577654
   4.02633077]
cost: 1.111171872244939
xvar: [197.39897312 115.87087293 240.73662231  80.15341216  47.76122197
  81.35730128  61.86914639   8.94259802   9.07611408   7.32170409
  10.18959801   8.79066269   5.70373288   3.47048265   1.66807949
  33.02965874  96.60394449   3.38531902  23.0669887   59.05846264
   4.44166654]
cost: 2.644515033642202
xvar: [1.52404044e+02 1.22613458e+02 2.38480502e+02 8.28389866e+01
 5.14728852e+01 7.64467355e+01 5.63008925e+01 5.84114564e+00
 9.34315852e+00 8.72365310e+00 1.10297894e+00 1.61688825e+01
 1.02948624e+01 2.57258270e+00 2.16352049e-01 2.19665214e+01
 9.01527252e+01 4.18202371e+00 3.80031960e+01 6.90324459e+01
 1.93374291e+00]
cost: 1.9251980524320176
xvar: [1.57698317e+02 1.23124101e+02 2.39050930e+02 7.57332071e+01
 4.16920230e+01 7.71118707e+01 5.31357095e+01 8.46295855e-01
 1.90953223e+01 1.61356207e+01 2.39034759e-01 1.18518308e+01
 1.91221159e+00 3.30454875e+00 3.24979217e+00 5.18087916e+01
 7.46645715e+01 3.85457393e+00 2.00808594e+01 5.71050164e+01
 1.78914748e+00]
cost: 4.9104141487675275
xvar: [151.62058003 120.77648904 238.31783432  75.89405982  53.67830413
  75.05987099  55.12516499  10.06778787   4.76776374  13.29326856
  19.08555732   8.90768197  14.53336107   4.50402915   0.27610286
  32.70098548  61.50704488   4.69028387  31.04711781  68.72442296
   4.77464845]
cost: 1.3747625214908574
xvar: [178.6192064  121.40572372 239.8123451   75.82857123  50.23469733
  75.11700694  61.20626063  19.44175829   2.06097469  17.29262019
  14.97899935  17.44113726   0.9259042    4.67531287   2.17965189
  24.72062758  95.14919279   3.06790929  33.60001152  68.86262716
   4.18569695]
cost: 1.4706593936260326
xvar: [120.88548111 122.08042566 239.19045045  77.97888206  48.51630487
  80.70179399  59.35444486  16.91397103   9.87052691   0.80960958
  11.84886495  18.47579151  14.23042642   0.43032517   1.89170074
  27.97506538  96.95853529   1.36001102  34.33690894  63.14833357
   1.84230245]
cost: 2.165281416675287
xvar: [1.19292115e+02 1.15748968e+02 2.39420408e+02 7.63680061e+01
 4.43189031e+01 8.20853342e+01 5.92910417e+01 8.67558068e+00
 5.78789281e+00 1.21820669e+01 5.63291917e+00 1.29436082e+01
 8.05311928e+00 8.55333161e-01 1.53720933e-01 4.87853543e+01
 9.49047828e+01 2.22073179e+00 3.15212332e+01 6.06417780e+01
 1.85359823e-01]
cost: 2.03492394135774
xvar: [125.42583322 119.86238912 238.35088797  82.60483711  43.79401692
  75.34170746  56.80503736  18.37352642   6.86293272  18.59498815
  14.45623811  13.20770478   3.9359368    1.3665558    4.97473801
  36.11235965  89.04517412   3.46028756  23.77161274  66.46077006
   4.15475933]
cost: 1.4267495252495785
xvar: [1.96828740e+02 1.19080517e+02 2.39390336e+02 7.72459986e+01
 4.80107090e+01 8.00882528e+01 5.52122466e+01 1.28803781e+01
 1.52046635e+01 1.27322866e+01 1.89472446e+01 2.08017610e+00
 8.92087291e+00 3.21537987e+00 1.38231670e+00 5.98415491e+01
 9.05873229e+01 1.28970952e-01 2.96907630e+01 5.75335951e+01
 6.59502246e-01]
cost: 0.949099103037405
xvar: [191.83206995 116.33002339 241.83510684  78.01260915  48.45011441
  79.56468975  65.31173118   5.75877464  17.25928332  15.28433036
   5.57772863  10.57861479  19.01633932   2.8897778    4.70075435
  44.7594267   77.07152375   4.96544919  35.89210862  67.59691211
   3.29777176]
cost: 1.9100531563481986
xvar: [1.66155446e+02 1.24981071e+02 2.38356094e+02 7.44470867e+01
 5.03324680e+01 7.52072201e+01 5.86547960e+01 6.63013378e+00
 7.79388467e+00 1.33111648e+01 1.57862207e+00 1.40267956e+01
 1.68861158e+01 4.34204535e+00 2.24917074e+00 3.31895617e+01
 9.18558460e+01 7.40197755e-01 4.20020251e+01 5.38769341e+01
 1.19723774e-01]
cost: 6.105093789103044
xvar: [144.73422444 116.2753652  241.86388266  75.76462377  42.32460775
  79.45928142  66.40350369   6.75458652  19.54071963   9.35761704
  18.57889794  17.11154794   6.34153872   4.01326467   3.27488491
  28.94052021  68.84248062   3.44780429  20.57762468  45.17093856
   3.60463304]
cost: 1.781275693992104
xvar: [186.41139098 118.21802962 239.72801717  76.47626475  52.67551994
  79.93308469  58.2405157   12.37219846  16.65236135   8.03604812
  16.22699065   0.82407633   7.97003514   0.30347995   2.37817115
  33.69827862  89.33278113   2.56415382  24.84847318  48.69940525
   2.8078529 ]
cost: 0.7819566048645602
xvar: [145.95141819 124.46909264 239.17641782  75.0855273   43.74219995
  79.15634522  63.05104522   2.69360886  14.93055595  18.39682866
  12.90626671  19.37757165  10.14587607   1.99524342   3.78432826
  39.65816855  85.04532628   3.56273622  37.10077803  60.8302255
   4.87121095]
cost: 4.425723145953884
xvar: [164.99379895 123.67104674 239.78875694  77.53054098  45.54018591
  79.52120858  59.72637907   6.91334801  17.08750131  13.95487362
   7.76942476  13.12025065   4.22631544   4.1611952    3.95852303
  33.90864687  77.91209697   2.42974588  29.47517835  49.39666833
   1.98655322]
cost: 5.601568073748373
xvar: [116.98959404 115.03025133 241.20740058  74.89780484  42.00692043
  77.71242761  49.6119029   11.92380208   2.90397607  14.02794357
   0.60691227   4.20280199  11.518465     3.58741982   4.90720346
  40.87305999  67.97069128   4.26410156  38.45767094  53.29347366
   0.82239357]
cost: 1.4471522362619942
xvar: [150.25288985 120.85414725 238.15145601  79.8316518   47.44918728
  79.02270009  51.34921341  12.98949328  16.10615616   6.64277135
   9.89703037  15.40234911   2.19620059   3.23422223   3.81643576
  59.58439074  73.95692135   0.62389312  32.26412241  47.95065742
   2.44614524]
cost: 3.19148793277897
xvar: [168.08105771 121.88496186 241.92209831  78.55788845  48.39226479
  76.68934611  51.08841893   9.16000096   4.20968551   2.3343227
  19.97958799  18.21098265   5.14739997   3.9962495    2.65876958
  34.50398222  68.90903945   3.92153895  34.91273719  59.3546928
   4.16227205]
cost: 2.095399300127643
xvar: [1.04778449e+02 1.24309724e+02 2.41612003e+02 8.24660293e+01
 4.98173698e+01 7.55282072e+01 5.48363892e+01 1.51321118e+01
 1.19517716e+01 1.31267769e+01 5.25091602e+00 1.43574971e+01
 3.81442584e+00 3.43775665e+00 3.95365469e+00 2.92696889e+01
 6.24392391e+01 1.65852757e-01 2.96172135e+01 6.73463301e+01
 2.61737736e+00]
cost: 5.616495464026846
xvar: [175.41489113 124.88217109 238.03440317  76.31315942  43.9903045
  79.85139908  54.63758935  10.17863603   4.35751407  15.97134463
  10.695041    14.95868045   6.03672725   2.34579532   4.50197121
  50.63020684  87.27769267   2.80147119  31.13321078  52.61998657
   3.72665574]
cost: 6.125971937750488
xvar: [185.12955265 117.38915932 238.39455309  80.52103636  49.22821552
  75.63585752  53.364274     6.02396502   9.20433431   0.52503524
   7.40849304  17.91605506  13.54534246   3.9677059    1.30171106
  27.15517632  71.82272116   1.48973729  27.80376742  67.67398213
   4.92291547]
cost: 1.5337845477201815
xvar: [157.32690301 121.26613713 238.41467131  81.20024305  42.48252796
  74.45179988  49.71095489   0.40216191  12.36685241  16.64516463
  11.06893867  14.49985625  16.69530942   1.76468002   4.23998491
  39.21698044  68.41397576   3.9975324   21.76851226  54.05094393
   1.03841673]
cost: 2.618458765952367
xvar: [124.8694228  115.52268304 239.67747787  81.08153483  45.44036586
  78.83349422  66.23410743   5.93862934  19.78613579  11.93009023
   6.82999818  16.87949054  17.33827663   1.8427163    4.73382498
  59.41052925  75.93808675   3.15907902  41.87358087  50.46970377
   1.54773045]
cost: 1.7677967906080894
xvar: [133.33012393 117.57455767 238.09446715  82.0047515   47.81634005
  75.46153168  60.90835599  19.94251299   7.24354025   5.51753372
   9.39172297  10.07960353  16.40520086   1.59947463   2.88142463
  58.10219588  85.01223218   4.33619045  22.22686795  45.96947824
   4.63755446]
cost: 1.5144340963115572
xvar: [114.98237535 115.26631116 240.1221251   79.12452107  54.23698402
  77.33008509  56.67163046  19.09031618   3.23754379  10.35700833
  11.61614966   1.7447723    8.82915201   4.13477771   4.88549982
  30.79266727  74.29006502   0.89023926  40.65265358  67.97526083
   2.83774106]
cost: 1.7046410233393208
xvar: [139.8271162  117.18126991 240.89431587  75.62817316  45.2166751
  78.04958084  53.86214018   3.55057021  12.53933098   1.67243607
   2.93291182   4.12730634   9.15549121   0.8797276    3.74468022
  38.49307781  62.38540553   2.5811656   34.99462113  61.66663771
   0.72607595]
cost: 1.290892782496626
xvar: [180.98182438 120.57639991 238.4582076   80.39341942  47.654351
  76.3999883   55.97311774  11.44490896  17.38584128   0.36629979
  14.14434957  11.38330855  10.57810289   4.62447905   4.25850668
  56.08888906  69.5302347    4.93672602  28.44010282  51.35121698
   3.61855547]
cost: 1.7899272508016697
xvar: [1.92166544e+02 1.17685485e+02 2.38759599e+02 7.57911414e+01
 4.79183991e+01 7.72137951e+01 5.98694625e+01 6.84536439e+00
 8.57099369e+00 1.43897796e+01 2.71081609e+00 3.90410473e+00
 1.70923738e+01 4.47475963e+00 1.34562918e-01 5.58050756e+01
 9.77340234e+01 9.14729941e-01 2.61107103e+01 6.38541754e+01
 3.45159493e+00]
cost: 0.7120466714906494
xvar: [1.50837157e+02 1.17607506e+02 2.39957484e+02 8.15173246e+01
 4.49797811e+01 7.76336001e+01 6.38230687e+01 1.21994864e+01
 1.09516874e+00 1.79677940e+01 1.95422975e+01 7.51979602e+00
 1.35836829e+01 4.94610215e-01 1.25969702e-01 3.72622370e+01
 6.80127881e+01 3.51471051e+00 3.83719098e+01 5.78842340e+01
 3.05625278e+00]
cost: 1.335784389394319
xvar: [148.21814525 124.74989178 241.53943143  82.0389413   47.38128097
  79.97356038  52.44758062  19.58851429  11.54909032   5.76144321
  13.27594431  13.74471996  13.2607966    2.57679369   3.66910417
  29.88464273  96.12967849   2.90271494  30.18203142  67.08382069
   3.41980035]
cost: 4.662244985220031
xvar: [193.06634326 121.64280991 240.47015697  77.6965012   41.93920314
  76.30828732  57.68002383  10.23510156  14.53324894   2.4784785
  10.77654942  13.9910944    8.54285895   1.32489238   1.76359392
  26.95208016  74.50898552   1.73616299  41.12066675  51.85349616
   0.31424028]
cost: 1.8335855813796413
xvar: [132.7938334  117.89040489 240.35849811  75.5413663   51.11916082
  75.67286977  65.73692423   6.30907048  10.53091548   6.87847119
   9.33115654   8.15312718   7.0424025    3.45312703   3.35221222
  41.7712105   93.50006495   4.20208347  29.21515907  57.36524711
   1.74601573]
cost: 1.4659894555524888
xvar: [198.25436662 118.07913246 240.13573352  81.51124163  41.09121093
  74.54926631  52.39656119  13.5391963   19.8773452   15.68430064
   5.98879372  15.36976207  10.84381615   0.57572035   2.62343832
  36.33115803  84.05382716   2.28808799  26.699012    65.95154234
   2.03810387]
cost: 0.8361953452835088
xvar: [106.3448592  121.18970483 240.55773492  76.78346507  41.80105756
  80.06631898  63.58783262  12.57335647   5.22980005  10.19477387
   5.40188313  17.17997167  11.7501376    4.87471563   4.60774569
  29.75578991  96.1932483    4.32337243  40.22631644  58.97320258
   2.10270971]
cost: 2.400966993147204
xvar: [142.20530257 120.02592875 241.11613246  79.07938917  45.78122796
  78.37976069  60.79878374  15.38868579   9.00097814   3.90247798
  15.91903315   2.87258315   7.52867061   2.9271865    1.56552204
  28.88108835  85.90008099   4.20794834  28.23347318  47.20354727
   0.55140182]
cost: 1.5559627456921996
xvar: [146.08819148 120.0617706  238.34210483  81.05398821  45.33755938
  74.04301788  58.84892672   2.26254994  14.12436481  13.56403697
  17.94921391  15.77280193  16.06273569   0.82527399   4.56577558
  58.70391992  85.17496155   1.13525082  22.59212045  61.24302476
   2.38118043]
cost: 1.6722581482499965
xvar: [1.42899767e+02 1.21095355e+02 2.38656043e+02 7.43385402e+01
 4.26894846e+01 7.46627069e+01 6.57745682e+01 8.94864677e+00
 1.31074659e+01 1.76406278e+01 1.69893832e+01 6.86695345e+00
 4.59034246e+00 4.18581091e+00 1.73676514e-01 3.08959314e+01
 8.96519214e+01 1.32724361e+00 3.73457419e+01 6.56197362e+01
 3.59850351e+00]
cost: 2.2541836861388034
xvar: [1.15343550e+02 1.21049462e+02 2.41228939e+02 7.76546784e+01
 5.38695042e+01 7.97463623e+01 5.92245129e+01 2.76860350e+00
 1.74372867e+01 6.51125748e+00 4.31716383e+00 1.35941532e+01
 9.92932225e+00 4.42798421e+00 1.54514026e+00 2.90958831e+01
 6.85246610e+01 4.84014593e+00 2.63572555e+01 4.50337261e+01
 1.56659190e-01]
cost: 2.0983074929181553
xvar: [129.80531708 118.67789408 239.03474347  81.39790447  44.52455442
  77.15480925  66.02371322   8.75255828  11.08696825   5.42328077
  14.91437211   8.42707384   2.40345267   2.07180462   0.96549082
  44.53411773  98.84813702   1.80264507  28.66971509  48.93152989
   2.90451746]
cost: 1.298593843826329
xvar: [187.47030841 116.22120168 239.9232155   79.60251381  48.78517985
  74.64164793  49.42132803  14.84179749  13.27540768  10.50670688
   6.04964655  11.09843475   0.47570533   3.16431593   2.98046653
  27.02848099  79.27898194   2.78267492  30.25103342  66.32583423
   4.08378337]
cost: 1.9112008685900501
xvar: [189.49283365 117.93989968 239.07677814  75.48490486  50.71473624
  75.4000935   55.67487728  11.57686349  12.1127528    1.31940002
  15.88529173  19.54351424   3.69794731   0.32731627   0.2445657
  22.30418654  87.53750795   1.58899745  40.7309487   55.5214255
   4.62232607]
cost: 1.0155932814519384
xvar: [124.15147893 121.81651706 239.3489062   75.93674653  49.93281507
  81.8664195   54.78642168   5.55907518   7.15030662   3.48378051
  10.45987977   0.27947456  17.93295898   4.72566707   1.17292175
  31.57836679  87.70625078   1.85201721  30.79840351  52.56758932
   1.86903602]
cost: 3.3814908011270663
xvar: [154.40062658 118.10534047 239.64535484  76.5961009   48.50637163
  78.01319239  50.49082599   4.36901188  18.38108674  15.22278011
   2.4677534   19.21439956   5.90677385   2.01879728   0.93681767
  30.65232072  73.14110862   1.872512    43.39378263  66.23255014
   0.86306063]
cost: 1.170978257365868
xvar: [176.29455729 120.54732237 241.62093188  74.64234806  52.86923409
  80.22216387  66.69631658  16.20017729   8.82813569  17.16409819
   8.46495882  15.11701138   8.23999169   1.46698642   3.88986245
  40.06146887  60.98760492   3.38004754  39.67314489  59.61933702
   2.30263055]
cost: 1.4152004040293762
xvar: [119.52856293 124.63916577 240.26754918  77.33577681  50.97229448
  80.24030232  65.92833466   0.4985202    4.01544873  16.69479537
   6.6147562   11.68708889  10.01765469   4.92672097   0.31252071
  57.27237898  89.34433542   2.33682325  43.65424246  68.62670713
   1.35650945]
cost: 5.761994165853423
xvar: [143.95522259 118.7959304  238.0868669   74.1712726   42.6128376
  77.27192183  61.97930327   5.70452175   5.72419036  19.21815888
   2.04724577  16.69645145  15.64866132   4.26879539   2.37068601
  57.47320335  73.54088801   3.88321923  37.29832751  61.32423078
   4.93894535]
cost: 1.2978834278752727
xvar: [159.62146968 115.66485794 239.72157959  76.64918682  52.71006317
  76.59530457  58.42639068  15.73459617   4.80763188  17.48042129
  10.25806572   7.58144389   6.48598404   1.23072163   0.55975121
  31.53953914  81.46018569   4.08083351  40.43378661  55.45473181
   2.7793671 ]
cost: 2.1953424307286453
xvar: [158.09734247 116.97447156 241.85382582  82.41043832  50.25345509
  75.02205552  50.68664158   6.15343869  14.42516241  19.29192851
  17.23778503   9.88142349   9.66426082   3.77949197   0.30112525
  49.71739046  67.04358425   1.05355457  34.15263613  56.6512049
   1.67062456]
cost: 0.8362240254484005
xvar: [163.63697331 123.27608894 240.22987803  75.96385985  52.14608323
  76.61398677  51.50624341  19.15978938  10.63171227  17.27684484
  16.65730953   3.33245355  11.17843528   2.27557547   4.18857227
  24.3648221   88.14597919   4.50971502  25.79723638  69.39761798
   2.86289332]
cost: 2.581226551044028
xvar: [110.24588199 115.19289572 239.23680924  82.17368208  43.37386923
  74.19010481  62.28909447   0.93262901  15.43406854   9.57573525
   7.52456399  17.55790916  18.51224844   3.17700858   2.04347973
  56.91371741  79.07886812   4.67727395  33.37305687  64.61886005
   2.71063713]
cost: 2.8301188440545335

KeyboardInterrupt:

In [171]:
for i in range(len(xvar_0)):
    x_test = xvar_0.copy()
    x_test[i] += 0.5  # small perturbation
    c1 = f_cost2(xvar_0, weight_f_long, weight_nrdd, weight_f_all)
    c2 = f_cost2(x_test, weight_f_long, weight_nrdd, weight_f_all)
    print(f"Var {i}: Δcost = {c2 - c1}")

xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [176.01, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2986266693425681
Var 0: Δcost = 0.0026650525864848618
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.71, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.28691580326936195
Var 1: Δcost = -0.009045813486721288
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.71, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2949880412222068
Var 2: Δcost = -0.0009735755338764474
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 76.141, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2979847773053474
Var 3: Δcost = 0.002023160549264158
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.589, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29677418607243855
Var 4: Δcost = 0.000812569316355316
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.963, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2967204445337699
Var 5: Δcost = 0.0007588277776866548
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.945, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2972484183818997
Var 6: Δcost = 0.0012868016258164583
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.867, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.295293060002023
Var 7: Δcost = -0.0006685567540602455
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 9.3571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.30035641257649215
Var 8: Δcost = 0.004394795820408914
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.948, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29548617029531765
Var 9: Δcost = -0.00047544646076558283
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.5016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2956356539525253
Var 10: Δcost = -0.00032596280355795537
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 8.3842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2961456798305818
Var 11: Δcost = 0.00018406307449858605
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 14.408, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29654449702578356
Var 12: Δcost = 0.0005828802697003255
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 1.2662499999999999, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2995725835889851
Var 13: Δcost = 0.003610966832901852
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.7386699999999999, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.301448999262683
Var 14: Δcost = 0.005487382506599747
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.919, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2954421486231346
Var 15: Δcost = -0.0005194681329486195
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.646, 4.489, 29.596, 63.282, 1.3673]
cost: 0.2976054713416465
Var 16: Δcost = 0.0016438545855632647
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.989, 29.596, 63.282, 1.3673]
cost: 0.30640136968087645
Var 17: Δcost = 0.01043975292479321
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 30.096, 63.282, 1.3673]
cost: 0.29610830625536033
Var 18: Δcost = 0.0001466894992770973
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.782, 1.3673]
cost: 0.2970791185390158
Var 19: Δcost = 0.0011175017829325729
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.3673]
cost: 0.29596161675608323
xvar: [175.51, 119.21, 241.21, 75.641, 53.089, 76.463, 49.445, 11.367, 8.8571, 10.448, 6.0016, 7.8842, 13.908, 0.76625, 0.23867, 30.419, 70.146, 4.489, 29.596, 63.282, 1.8673]
cost: 0.3068750146517314
Var 20: Δcost = 0.010913397895648158